// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJ1xU-gFHXUH_uyzBu1vAHL6vTKHMYU8',
    appId: '1:609242910939:web:c450dc6ad59f271feefcfe',
    messagingSenderId: '609242910939',
    projectId: 'services-storage-b3afa',
    authDomain: 'services-storage-b3afa.firebaseapp.com',
    storageBucket: 'services-storage-b3afa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rjj3_aTV2YFuxKj_uvPpbw4TSJN-C2M',
    appId: '1:609242910939:android:cf97c27638a1d13feefcfe',
    messagingSenderId: '609242910939',
    projectId: 'services-storage-b3afa',
    storageBucket: 'services-storage-b3afa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyAMcwAhOdMnDQkw7_1KftglPdF0t_k4',
    appId: '1:609242910939:ios:3063538959bc2e0beefcfe',
    messagingSenderId: '609242910939',
    projectId: 'services-storage-b3afa',
    storageBucket: 'services-storage-b3afa.firebasestorage.app',
    iosBundleId: 'com.example.servicesManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmyAMcwAhOdMnDQkw7_1KftglPdF0t_k4',
    appId: '1:609242910939:ios:3063538959bc2e0beefcfe',
    messagingSenderId: '609242910939',
    projectId: 'services-storage-b3afa',
    storageBucket: 'services-storage-b3afa.firebasestorage.app',
    iosBundleId: 'com.example.servicesManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACJ1xU-gFHXUH_uyzBu1vAHL6vTKHMYU8',
    appId: '1:609242910939:web:f07188bc7dd86bdbeefcfe',
    messagingSenderId: '609242910939',
    projectId: 'services-storage-b3afa',
    authDomain: 'services-storage-b3afa.firebaseapp.com',
    storageBucket: 'services-storage-b3afa.firebasestorage.app',
  );
}
